name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Restore nuget packages
      run: nuget restore SharpMap.sln
    - name: MSBuild SharedAssemblyVersion
      run: msbuild SharpMap.targets /t:Version

# For unknown reason the build with "dotnet build" fails with hundreds of errors, while the "classic" one works
    - name: Build with MSBuild
      run: msbuild SharpMap.sln /p:Configuration=ReleaseDotNet /t:Version

#    - name: Build with dotnet
#      env:
#        DOTNET_CLI_TELEMETRY_OPTOUT: 1
#      run: dotnet build SharpMap.sln --configuration ReleaseDotNet

    - name: Setup NUnit TestRunner
      run: nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
    - name: Perform tests
      run: ../../../../testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe UnitTests.dll
      working-directory:
        ./UnitTests/bin/Release/net472

#    - name: Publish packages
#      if: success()
#      env:
#        MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
#      run: dotnet nuget push SharpMap.Packages/SharpMap.*.nupkg --api-key $MYGET_API_KEY --source https://www.myget.org/F/sharpmap/api/v2/package --skip-duplicate

#    - name: Upload
#      uses: actions/upload-artifact@v1
#      with:
#        name: NuGet Package Files
#        path: SharpMap.Packages
